### ISSUE TITLE
Multi-blog: custom settings per blog

### ISSUE THREAD

**Issue by jqno** [ludovicchabant/PieCrust#101]
Hi!

I have another annoying multi-blog question :). Is there a way to refer to "custom", per-blog settings in config.yml? I've been looking, but I couldn't find it...

Specifically, say that I have a `config.yml` like this:

```
site:
    title: This is my blog!
    blogs: [ post, another_blog ]

post:
    sub_title: My posts!

another_blog:
    sub_title: This is something else!
```

I'd like to refer to these settings in my templates. For example, in `default.html`:

```
<title>{{ site.title }} &mdash; {{ site.current_blog.sub_title }}</title>
```

Obviously, I just made up `site.current_blog`.

Currently, I'm using this:

```
{% if page.blog == "another_blog" %}
  {% set current_blog = another_blog %}
{% else %}
  {% set current_blog = post %}
{% endif %}
<title>{{ site.title }} &mdash; {{ current_blog.sub_title }}</title>
```

It works, but it's quite ugly, and also has to be repeated in every file where it's needed...
