### ISSUE TITLE
adding themes_sources:

### ISSUE THREAD

**Issue by mistergraphx** [ludovicchabant/PieCrust#132]
Hi & thanks for this great tool.

I tried to add a themes_sources: config to create multiple themes for the generated sites, like you describe in this article.
http://ludovic.chabant.com/devblog/2012/11/06/themes-in-piecrust/

But 
`chef themes install Theme1`
retur  `Can't find a single theme named: Theme1`

my config.yml file : 

```
site:
    title: 'Projet 1'
    description: 'Base de démarrage HTML5'
    author: Arnaud B. (Mist. GraphX)
    pretty_urls: false
    auto_formats:
        md: markdown
markdown:
    use_markdown_extra: true
themes_sources:
    - ../_themes
smartypants:
    enable: true
```

The file structure is 

/
|-> _themes
|  |->theme1
|  |->theme2
|-> Site1
|  |-> _content

Could you explain me where i'm wrong ?.
