### ISSUE TITLE
.sitemap file processor still working?

### ISSUE THREAD

**Issue by jevets** [ludovicchabant/PieCrust#48]
I'm either missing something with the sitemap processor or maybe it's not working anymore.

Can anyone confirm if it still works?

I've tried lots of combinations:

`_content/pages/sitemap.xml.sitemap`:

```

---
single_page: true
layout: none
format: none

---
locations:
  - url: /
  - url: /about
```

```

---
single_page: true
layout: none
format: none
locations:
  - url: /
  - url: /about

---
```

```
locations:
  - url: /
  - url: /about
```

Always ends up getting baked as either
- sitemap.xml.sitemap/index.html
- sitemap.xml.sitemap

No matter what I try, the output isn't XML at all. No errors thrown or anything.

My config.yml doesn't list processors under baker, so the .sitemap file should be picked up by default.

Thank you
