### ISSUE TITLE
Usage of site.root

### ISSUE THREAD

**Issue by reubenbijl** [ludovicchabant/PieCrust#65]
Check out current stable branch.

Edit _index.html page in the default website to include {{ site.root }} somewhere in the page.

Edit config.yml to include site.root as in this example

```
site:
    title: Your New PieCrust Website
    description: A sample website running with PieCrust
    author: Anonymous
    pretty_urls: false
    root: http://mydomain.com/
```

Run  chef showconfig, result shows site root

```
site:
  title: Your New PieCrust Website
  root: http://mydomain.com/
```

Serve page using chef serve, {{site.root}} shows as '/', expected that it would show http://mydomain.com/
